name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Catalog
      run: make catalog

    - name: Validate
      uses: joelanford/opm-validate@main
      with:
        catalog: catalog

    - name: Release
      if: github.event_name == 'push'
      uses: grokspawn/action-pull-request-another-repo@v1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_folder: './catalog/*'
        destination_repo: 'scoheb/cool-catalog'
        destination_folder: './catalog/'
        destination_head_branch: cool-catalog-contributor-${{ github.actor }}
        user_email: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        user_name: ${{ github.actor }}
